version: '3.4'

services:
  client:
    image: omm
    build:
      context: ./OMM
      dockerfile: Dockerfile
    container_name: omm-client
    command: npm start
    volumes:
      - ./OMM/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network
  server:
    build:
      context: ./OMMExpressApp
      dockerfile: Dockerfile
    image: omm-express-app
    container_name: omm-express-app-server
    volumes:
      - ./OMMExpressApp/:/app
      - /usr/src/app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  node_modules:
  web-root:
    driver: local